SET TRANSACTION ISOLATION LEVEL READ COMMITTED
--SET TRANSACTION ISOLATION LEVEL  REPEATABLE READ

BEGIN TRANSACTION
SELECT * FROM Partners
WAITFOR DELAY '00:00:05';
SELECT * FROM Partners
COMMIT TRANSACTION