SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE

BEGIN TRANSACTION
SELECT * FROM Partners
WHERE PaRevenue>10000
WAITFOR DELAY '00:00:05';
SELECT * FROM Partners
WHERE PaRevenue>10000
COMMIT TRANSACTION