

--SET TRAN ISOLATION LEVEL Read Committed

SET TRAN ISOLATION LEVEL SNAPSHOT

BEGIN TRANSACTION
WAITFOR DELAY '00:00:05'
UPDATE Partners SET PaRevenue = 123 WHERE Paid=4;
COMMIT TRANSACTION


--SELECT * FROM Partners 
--ALTER DATABASE [League of Legends Competition] SET ALLOW_SNAPSHOT_ISOLATION OFF;